// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpyrrctzuudgokhkucli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZweXJyY3R6dXVkZ29raGt1Y2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTgxMTUsImV4cCI6MjA2NzkzNDExNX0.3vJsiGw7TFFlY-aAec7pgh34lhtzMFbOfi-vBJUrawI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});